default_platform(:ios)

platform :ios do

  desc "Run tests and get coverage"
  lane :coverage do
    run_tests(
      scheme: "Main",
      device: "iPhone 16",
      code_coverage: true,
      output_directory: "test_output",
      result_bundle: true
    )

    xcov(
      scheme: "Main",
      output_directory: "coverage_output",
      html_report: true,
      json_report: true,
      minimum_coverage_percentage: 60.0,
      include_targets: "Main.app"
    )

    report_path = Dir.glob("coverage_output/tmp/*")
                 .find { |file| File.file?(file) && File.basename(file).start_with?("report.json") }

    if report_path
      report = JSON.parse(File.read(report_path))
      coverage_pct = report["coverage_percentage"].to_f / 100

      File.write("coverage_output/coverage_badge.json", JSON.generate({
        schemaVersion: 1,
        label: "coverage",
        message: "#{(coverage_pct * 100).round(1)}%",
        color: coverage_pct > 0.8 ? "brightgreen" : coverage_pct > 0.6 ? "yellow" : "red"
      }))
    else
      UI.important("skipping badge generation")

      File.write("coverage_output/coverage_badge.json", JSON.generate({
        schemaVersion: 1,
        label: "coverage",
        message: "N/A",
        color: "lightgrey"
      }))
    end
  end
end
